In [1]:
import pandas as pd

In [2]:
ls = pd.read_csv("/Users/rrodr102/Desktop/Python/LineupData0110/Lineup Data/lineup_summary_all_games2.csv")
#pairs = pd.read_csv("/Users/rrodr102/Desktop/Python/LineupData0110/Lineup Data/pair_analysis_all_games2.csv")
indiv = pd.read_csv("/Users/rrodr102/Desktop/Python/LineupData0110/Lineup Data/individual_summary_all_games2.csv")
trios = pd.read_csv("/Users/rrodr102/Desktop/Python/LineupData0110/Lineup Data/trio_analysis_all_games2.csv")

### Show lineups with more than 22 possessions

In [3]:
display(ls[['lineup', 'rel_PM_p40','poss_total','PM_p40', 'net_rtg', 'minutes',
       'o_poss', 'd_poss',   'off_rtg',
       'def_rtg', 'team_off_rtg', 'team_def_rtg', 'team_PM_p40']][ls['poss_total']>22].sort_values('poss_total', ascending =False))

,lineup,rel_PM_p40,poss_total,PM_p40,net_rtg,minutes,o_poss,d_poss,off_rtg,def_rtg,team_off_rtg,team_def_rtg,team_PM_p40
0,JL-AM-IK-MH-CH,12.281,394.252,14.725,18.325,124.955,202.005,192.248,110.393,92.069,104.158,100.663,2.444
1,JL-AM-AC-MH-CH,-2.444,126.588,0.000,3.299,35.728,62.262,64.327,102.792,99.492,104.158,100.663,2.444
3,JL-AM-IK-MH-PR,10.492,85.741,12.936,13.634,24.737,43.760,41.981,127.971,114.337,104.158,100.663,2.444
2,AM-AC-ZO-MH-CH,-22.707,82.005,-20.262,-22.853,25.663,39.430,42.575,103.982,126.835,104.158,100.663,2.444
4,AM-IK-ZO-MH-CH,-17.917,73.165,-15.473,-12.084,23.267,34.455,38.710,101.582,113.666,104.158,100.663,2.444
6,AM-AC-ZO-MH-PR,19.807,62.045,22.251,40.448,17.977,29.520,32.525,105.014,64.566,104.158,100.663,2.444
5,JL-AM-IK-PR-CH,-17.554,56.900,-15.109,-19.657,18.532,27.720,29.180,86.580,106.237,104.158,100.663,2.444
7,JL-AC-IK-MH-CH,-2.444,48.700,0.000,5.002,14.730,23.780,24.920,109.336,104.334,104.158,100.663,2.444
10,JL-AM-AC-MH-PR,0.865,45.813,3.309,-6.170,12.088,24.190,21.623,90.947,97.117,104.158,100.663,2.444
8,AM-IK-ZO-KJ-CH,27.859,44.590,30.303,33.659,13.200,24.190,20.400,82.679,49.020,104.158,100.663,2.444
11,JL-AM-ZO-MH-CH,-27.628,43.300,-25.184,-8.068,11.118,19.320,23.980,108.696,116.764,104.158,100.663,2.444
9,AM-AC-ZO-KJ-PR,-2.444,37.207,0.000,8.577,12.402,17.617,19.590,85.146,76.570,104.158,100.663,2.444
12,AM-IK-ZO-MH-PR,19.210,36.250,21.654,15.638,11.083,19.730,16.520,106.437,90.799,104.158,100.663,2.444
17,JL-IK-ZO-MH-CH,50.547,33.595,52.992,51.551,7.548,17.395,16.200,137.971,86.420,104.158,100.663,2.444
13,JL-AC-IK-KJ-CH,-15.067,30.050,-12.623,-8.661,9.507,14.250,15.800,105.263,113.924,104.158,100.663,2.444
16,JL-AC-ZO-MH-CH,34.253,29.260,36.697,38.451,7.630,15.330,13.930,117.417,78.966,104.158,100.663,2.444
14,JL-AM-IK-KJ-CH,30.368,26.385,32.812,78.455,8.533,11.055,15.330,117.594,39.139,104.158,100.663,2.444
21,JL-AM-AC-KJ-CH,-65.723,25.380,-63.279,-89.975,6.953,12.850,12.530,85.603,175.579,104.158,100.663,2.444
18,AM-IK-ZO-PR-CH,-24.263,25.330,-21.818,-12.345,7.333,10.930,14.400,64.044,76.389,104.158,100.663,2.444
15,AC-IK-ZO-MH-CH,28.928,24.790,31.373,55.143,7.650,11.930,12.860,117.351,62.208,104.158,100.663,2.444
19,AM-AC-ZO-PR-CH,-13.436,22.660,-10.992,-36.570,7.278,12.000,10.660,141.667,178.236,104.158,100.663,2.444
23,JL-AC-IK-MH-PR,17.952,22.660,20.397,-1.038,5.883,12.400,10.260,145.161,146.199,104.158,100.663,2.444
20,AM-AC-IK-MH-CH,-24.822,22.530,-22.378,-40.659,7.150,11.800,10.730,33.898,74.557,104.158,100.663,2.444

## Top 10 Lineups [that have played sufficient def possessions]

In [5]:
top10 = ls.sort_values('d_poss', ascending=False).head(11)
top10.insert(0, 'Index', range(1, len(top10) + 1))
def color_pm(val):
    color = ''
    if val > 0:
        color = f'background-color: rgba(0, 200, 0, {min(val/20,1):.2f})'
    elif val < 0:
        color = f'background-color: rgba(255, 0, 0, {min(abs(val)/20,1):.2f})'
    return color

cols = ['Index','lineup', 'poss_total', 'minutes', 'PM_p40', 'rel_PM_p40', 'off_rtg', 'def_rtg']
top10 = top10[cols]
top10 = top10.round(1)

top10.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['rel_PM_p40']).format({
    'poss_total':'{:.1f}',
    'minutes' : '{:.1f}',
    'plus_minus': '{:.1f}',

    'PM_p40': '{:.1f}',
    'rel_PM_p40':'{:.1f}',

    'off_rtg': '{:.2f}',
    'def_rtg': '{:.2f}'
}
                                                         )

/var/folders/qh/zhr4gq8s5px2ff46zwfdk90hy3y30j/T/ipykernel_98387/1851225626.py:15: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  top10.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['rel_PM_p40']).format({

## 2-Player Combo analysis - 6 games

##### Most minutes played

In [6]:
temp = pairs[pairs['minutes']>60]
display(temp[['player1','player2','minutes','PM_p40','net_rtg']].sort_values('minutes',ascending=False).reset_index(drop= True))
display(
    temp[['player1', 'player2', 'minutes', 'PM_p40', 'net_rtg']]
    .sort_values('minutes', ascending=False)
    .reset_index(drop=True)
    .style.format({
        'minutes': '{:.1f}',
        'PM_p40': '{:.1f}',
        'net_rtg': '{:.1f}'
    })
)

   player1 player2  minutes     PM_p40    net_rtg
0       AM      CH  161.770   2.719911   3.453013
1       AM      MH  158.221   5.056219   4.664799
2       AM      IK  144.606   9.404866  14.787709
3       JL      AM  130.523   3.064594   0.544092
4       IK      CH  125.485   9.562896  15.628474
5       MH      CH  121.909   5.249817   6.752391
6       IK      MH  120.010  10.665778  12.895234
7       JL      MH  119.875   7.340980   7.313590
8       JL      CH  115.330   9.364432  12.503795
9       JL      IK  112.772  10.640939  15.030938
10      AM      ZO   89.638   5.354872  10.917897
11      AM      AC   85.378  -0.937010  -2.966647
12      AM      PR   83.509   1.915961  -0.486687
13      ZO      MH   62.311   9.629118  17.860093
14      AC      CH   61.976  -7.744934  -9.426653
15      AC      MH   60.906   3.940498   6.393472

#### Best PM_p40

In [7]:
temp = pairs[pairs['minutes']>60]
display(temp[['player1','player2','minutes','PM_p40','net_rtg']].sort_values('PM_p40',ascending=False).reset_index(drop= True))

   player1 player2  minutes     PM_p40    net_rtg
0       IK      MH  120.010  10.665778  12.895234
1       JL      IK  112.772  10.640939  15.030938
2       ZO      MH   62.311   9.629118  17.860093
3       IK      CH  125.485   9.562896  15.628474
4       AM      IK  144.606   9.404866  14.787709
5       JL      CH  115.330   9.364432  12.503795
6       JL      MH  119.875   7.340980   7.313590
7       AM      ZO   89.638   5.354872  10.917897
8       MH      CH  121.909   5.249817   6.752391
9       AM      MH  158.221   5.056219   4.664799
10      AC      MH   60.906   3.940498   6.393472
11      JL      AM  130.523   3.064594   0.544092
12      AM      CH  161.770   2.719911   3.453013
13      AM      PR   83.509   1.915961  -0.486687
14      AM      AC   85.378  -0.937010  -2.966647
15      AC      CH   61.976  -7.744934  -9.426653

In [8]:
import ipywidgets as widgets
from IPython.display import display

# trios is your DataFrame with columns: player1, player2, player3, minutes, net_rtg, PM_p40, etc.

# Get unique players from all 3 columns
players = sorted(
    set(pairs["player1"]).union(pairs["player2"])
)

def color_pm(val):
    if val is None:
        return ""
    try:
        v = float(val)
    except Exception:
        return ""
    if v > 0:
        return f"background-color: rgba(0, 200, 0, {min(v/20, 1):.2f})"
    elif v < 0:
        return f"background-color: rgba(255, 0, 0, {min(abs(v)/20, 1):.2f})"
    return ""

def show_combinations(player, sort_by="d_poss", ascending=False):
    mask = (
        (pairs["player1"] == player)
        | (pairs["player2"] == player)
    )
    df = pairs[mask].copy()
    df = df[df['minutes'] > 11]

    if sort_by in df.columns:
        df = df.sort_values(by=sort_by, ascending=ascending)

    display(
        df.style
        .applymap(color_pm, subset=["PM_p40"])
        .applymap(color_pm, subset=["net_rtg"])
        .format({
            "PM_p40": "{:.1f}",
            "net_rtg": "{:.1f}",
            "minutes": "{:.1f}",
            "plus_minus": "{:.1f}",
            "o_poss": "{:.1f}",
            "d_poss": "{:.1f}",
            "pts_for": "{:.1f}",
            "pts_against": "{:.1f}",
            "off_rtg": "{:.1f}",
            "def_rtg": "{:.1f}",
        })
    )

dropdown = widgets.Dropdown(options=players, description="Player:")
widgets.interactive(show_combinations, player=dropdown)

interactive(children=(Dropdown(description='Player:', options=('AC', 'AM', 'AM7', 'CH', 'IK', 'JL', 'KJ', 'MH'…

### Best Player Combos

In [9]:
# Combine player pairs so that ('IK', 'ZO') and ('ZO', 'IK') are treated as the same
# Filter pairs with at least 60 defensive possessions played together
filtered_pairs = pairs[pairs['d_poss'] >= 60].copy()
pairs_norm = filtered_pairs.copy()
pairs_norm['pair'] = pairs_norm.apply(lambda row: tuple(sorted([row['player1'], row['player2']])), axis=1)

# Group by normalized pair and aggregate stats
agg_pairs = pairs_norm.groupby('pair').agg({
    'minutes': 'sum',
    'net_rtg': 'mean',
    'PM_p40': 'mean',
    'pts_for': 'sum',
    'pts_against': 'sum',
    'plus_minus': 'sum',
    'o_poss': 'sum',
    'd_poss': 'sum',
    'off_rtg': 'mean',
    'def_rtg': 'mean'
}).reset_index()

# Only keep combos with at least 50 defensive possessions
agg_pairs = agg_pairs.sort_values('PM_p40',ascending=False)
# Split pair back into player1/player2 columns for display
agg_pairs[['player1', 'player2']] = pd.DataFrame(agg_pairs['pair'].tolist(), index=agg_pairs.index)
agg_pairs = agg_pairs.drop(columns=['pair'])

# Reorder columns for display
display_cols = ['player1', 'player2','minutes', 'net_rtg', 'PM_p40', 'plus_minus', 'o_poss', 'd_poss', 'pts_for', 'pts_against', 'off_rtg', 'def_rtg']
agg_pairs = agg_pairs[display_cols].round(2)

# Apply colormap formatting
def color_pm(val):
    color = ''
    if val > 0:
        color = f'background-color: rgba(0, 200, 0, {min(val/20,1):.2f})'
    elif val < 0:
        color = f'background-color: rgba(255, 0, 0, {min(abs(val)/20,1):.2f})'
    return color
    # Set white background for the styled DataFrame
    agg_pairs = agg_pairs.style.set_properties(**{'background-color': 'white'})
agg_pairs.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['net_rtg']).format({
    'minutes': '{:.1f}',
    'net_rtg': '{:.1f}',
    'PM_p40': '{:.1f}',
    'plus_minus': '{:.1f}',
    'o_poss': '{:.1f}',
    'd_poss': '{:.1f}',
    'pts_for': '{:.1f}',
    'pts_against': '{:.1f}',
    'off_rtg': '{:.1f}',
    'def_rtg': '{:.1f}',
})

/var/folders/qh/zhr4gq8s5px2ff46zwfdk90hy3y30j/T/ipykernel_98387/3703137032.py:41: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  agg_pairs.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['net_rtg']).format({

### WORST PLAYER COMBOS

In [11]:
# Combine player pairs so that ('IK', 'ZO') and ('ZO', 'IK') are treated as the same
# Filter pairs with at least 60 defensive possessions played together
filtered_pairs = pairs[pairs['d_poss'] >= 80].copy()
pairs_norm = filtered_pairs.copy()
pairs_norm['pair'] = pairs_norm.apply(lambda row: tuple(sorted([row['player1'], row['player2']])), axis=1)

# Group by normalized pair and aggregate stats
agg_pairs = pairs_norm.groupby('pair').agg({
    'minutes': 'sum',
    'net_rtg': 'mean',
    'PM_p40': 'mean',
    'pts_for': 'sum',
    'pts_against': 'sum',
    'plus_minus': 'sum',
    'o_poss': 'sum',
    'd_poss': 'sum',
    'off_rtg': 'mean',
    'def_rtg': 'mean'
}).reset_index()

# Only keep combos with at least 50 defensive possessions
agg_pairs = agg_pairs[agg_pairs['d_poss'] >= 35]
agg_pairs = agg_pairs.sort_values('PM_p40',ascending=True)
# Split pair back into player1/player2 columns for display
agg_pairs[['player1', 'player2']] = pd.DataFrame(agg_pairs['pair'].tolist(), index=agg_pairs.index)
agg_pairs = agg_pairs.drop(columns=['pair'])

# Reorder columns for display
display_cols = ['player1', 'player2', 'minutes', 'net_rtg', 'PM_p40', 'plus_minus', 'o_poss', 'd_poss', 'pts_for', 'pts_against', 'off_rtg', 'def_rtg']
agg_pairs = agg_pairs[display_cols].round(2)

# Apply colormap formatting
def color_pm(val):
    color = ''
    if val > 0:
        color = f'background-color: rgba(0, 200, 0, {min(val/20,1):.2f})'
    elif val < 0:
        color = f'background-color: rgba(255, 0, 0, {min(abs(val)/20,1):.2f})'
    return color
    # Set white background for the styled DataFrame
    agg_pairs = agg_pairs.style.set_properties(**{'background-color': 'white'})
agg_pairs.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['net_rtg']).format({
    'minutes': '{:.1f}',
    'net_rtg': '{:.1f}',
    'PM_p40': '{:.1f}',
    'plus_minus': '{:.1f}',
    'o_poss': '{:.1f}',
    'd_poss': '{:.1f}',
    'pts_for': '{:.1f}',
    'pts_against': '{:.1f}',
    'off_rtg': '{:.1f}',
    'def_rtg': '{:.1f}',
})

/var/folders/qh/zhr4gq8s5px2ff46zwfdk90hy3y30j/T/ipykernel_98387/1005601952.py:42: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  agg_pairs.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['net_rtg']).format({

### 3 Player Combos

In [ ]:
import ipywidgets as widgets
from IPython.display import display

# trios is your DataFrame with columns: player1, player2, player3, minutes, net_rtg, PM_p40, etc.

# Get unique players from all 3 columns
players = sorted(
    set(trios["player1"]).union(trios["player2"]).union(trios["player3"])
)

def color_pm(val):
    if val is None:
        return ""
    try:
        v = float(val)
    except Exception:
        return ""
    if v > 0:
        return f"background-color: rgba(0, 200, 0, {min(v/20, 1):.2f})"
    elif v < 0:
        return f"background-color: rgba(255, 0, 0, {min(abs(v)/20, 1):.2f})"
    return ""

def show_combinations(player, sort_by="d_poss", ascending=False):
    mask = (
        (trios["player1"] == player)
        | (trios["player2"] == player)
        | (trios["player3"] == player)
    )
    df = trios[mask].copy()
    df = df[df['minutes'] > 30]

    if sort_by in df.columns:
        df = df.sort_values(by=sort_by, ascending=ascending)
    keepcols = ['player1','player2','player3','minutes','rel_PM_p40','PM_p40','net_rtg','def_rtg','off_rtg']
    df = df[keepcols]
    display(
        df.style
        .applymap(color_pm, subset=["PM_p40"])
        .applymap(color_pm, subset=["net_rtg"])
        .format({
            "net_rtg": "{:.1f}",
            "minutes": "{:.1f}",
            "off_rtg": "{:.1f}",
            "def_rtg": "{:.1f}",
            "PM_p40":"{:.1f}",
            "rel_PM_p40":"{:.1f}",
        })
    )

dropdown = widgets.Dropdown(options=players, description="Player:")
widgets.interactive(show_combinations, player=dropdown)

interactive(children=(Dropdown(description='Player:', options=('AC', 'AM', 'AM7', 'CH', 'IK', 'JL', 'KJ', 'MH'…

In [11]:
import ipywidgets as widgets
from IPython.display import display, clear_output

accordion_children = []
titles = []

for player in players:
    out = widgets.Output()
    with out:
        show_combinations(player)
    accordion_children.append(out)
    titles.append(player)

accordion = widgets.Accordion(children=accordion_children)
for i, title in enumerate(titles):
    accordion.set_title(i, title)

display(accordion)

Accordion(children=(Output(), Output(), Output(), Output(), Output(), Output(), Output(), Output(), Output()),…

### of combos that have played at least 79 defensive possessions which ones have the highest PM_p40

In [16]:
# Combine player pairs so that ('IK', 'ZO') and ('ZO', 'IK') are treated as the same
# Filter pairs with at least 60 defensive possessions played together
filtered_pairs = trios[trios['d_poss'] >= 80].copy()
pairs_norm = filtered_pairs.copy()
pairs_norm['pair'] = pairs_norm.apply(lambda row: tuple(sorted([row['player1'], row['player2'], row['player3']])), axis=1)

# Group by normalized pair and aggregate stats
agg_pairs = pairs_norm.groupby('pair').agg({
    'minutes': 'sum',
    'net_rtg': 'mean',
    'PM_p40': 'mean',
    'pts_for': 'sum',
    'pts_against': 'sum',
    'plus_minus': 'sum',
    'o_poss': 'sum',
    'd_poss': 'sum',
    'off_rtg': 'mean',
    'def_rtg': 'mean'
}).reset_index()

# Only keep combos with at least 50 defensive possessions
agg_pairs = agg_pairs.sort_values('PM_p40',ascending=False)
# Split pair back into player1/player2 columns for display
agg_pairs[['player1', 'player2', 'player3']] = pd.DataFrame(agg_pairs['pair'].tolist(), index=agg_pairs.index)
agg_pairs = agg_pairs.drop(columns=['pair'])

# Reorder columns for display
display_cols = ['player1', 'player2', 'player3','minutes', 'net_rtg', 'PM_p40', 'plus_minus', 'o_poss', 'd_poss', 'pts_for', 'pts_against', 'off_rtg', 'def_rtg']
agg_pairs = agg_pairs[display_cols].round(2)

# Apply colormap formatting
def color_pm(val):
    color = ''
    if val > 0:
        color = f'background-color: rgba(0, 200, 0, {min(val/20,1):.2f})'
    elif val < 0:
        color = f'background-color: rgba(255, 0, 0, {min(abs(val)/20,1):.2f})'
    return color
    # Set white background for the styled DataFrame
    agg_pairs = agg_pairs.style.set_properties(**{'background-color': 'white'})
agg_pairs.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['net_rtg']).format({
    'minutes': '{:.1f}',
    'net_rtg': '{:.1f}',
    'PM_p40': '{:.1f}',
    'plus_minus': '{:.1f}',
    'o_poss': '{:.1f}',
    'd_poss': '{:.1f}',
    'pts_for': '{:.1f}',
    'pts_against': '{:.1f}',
    'off_rtg': '{:.1f}',
    'def_rtg': '{:.1f}',
})

/var/folders/qh/zhr4gq8s5px2ff46zwfdk90hy3y30j/T/ipykernel_98387/1238414936.py:41: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  agg_pairs.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['net_rtg']).format({

In [17]:
# Combine player pairs so that ('IK', 'ZO') and ('ZO', 'IK') are treated as the same
# Filter pairs with at least 60 defensive possessions played together
filtered_pairs = trios[trios['d_poss'] >= 80].copy()
pairs_norm = filtered_pairs.copy()
pairs_norm['pair'] = pairs_norm.apply(lambda row: tuple(sorted([row['player1'], row['player2'], row['player3']])), axis=1)

# Group by normalized pair and aggregate stats
agg_pairs = pairs_norm.groupby('pair').agg({
    'minutes': 'sum',
    'net_rtg': 'mean',
    'PM_p40': 'mean',
    'pts_for': 'sum',
    'pts_against': 'sum',
    'plus_minus': 'sum',
    'o_poss': 'sum',
    'd_poss': 'sum',
    'off_rtg': 'mean',
    'def_rtg': 'mean'
}).reset_index()

# Only keep combos with at least 50 defensive possessions
agg_pairs = agg_pairs[agg_pairs['d_poss'] >= 35]
agg_pairs = agg_pairs.sort_values('PM_p40',ascending=True)
# Split pair back into player1/player2 columns for display
agg_pairs[['player1', 'player2','player3']] = pd.DataFrame(agg_pairs['pair'].tolist(), index=agg_pairs.index)
agg_pairs = agg_pairs.drop(columns=['pair'])

# Reorder columns for display
display_cols = ['player1', 'player2', 'player3', 'minutes', 'net_rtg', 'PM_p40', 'plus_minus', 'o_poss', 'd_poss', 'pts_for', 'pts_against', 'off_rtg', 'def_rtg']
agg_pairs = agg_pairs[display_cols].round(2)

# Apply colormap formatting
def color_pm(val):
    color = ''
    if val > 0:
        color = f'background-color: rgba(0, 200, 0, {min(val/20,1):.2f})'
    elif val < 0:
        color = f'background-color: rgba(255, 0, 0, {min(abs(val)/20,1):.2f})'
    return color
    # Set white background for the styled DataFrame
    agg_pairs = agg_pairs.style.set_properties(**{'background-color': 'white'})
agg_pairs.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['net_rtg']).format({
    'minutes': '{:.1f}',
    'net_rtg': '{:.1f}',
    'PM_p40': '{:.1f}',
    'plus_minus': '{:.1f}',
    'o_poss': '{:.1f}',
    'd_poss': '{:.1f}',
    'pts_for': '{:.1f}',
    'pts_against': '{:.1f}',
    'off_rtg': '{:.1f}',
    'def_rtg': '{:.1f}',
})

/var/folders/qh/zhr4gq8s5px2ff46zwfdk90hy3y30j/T/ipykernel_98387/219325819.py:42: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  agg_pairs.style.applymap(color_pm, subset=['PM_p40']).applymap(color_pm, subset=['net_rtg']).format({

## Individuals with the highest PM_p40

In [18]:

indiv_sorted = indiv.sort_values('PM_p40', ascending=False).reset_index(drop=True)

indiv_sorted = indiv_sorted.loc[:, ~indiv_sorted.columns.str.contains('^Unnamed')]


def color_pm(val):
    color = ''
    if val > 0:
        color = f'background-color: rgba(0, 200, 0, {min(val/20,1):.2f})'
    elif val < 0:
        color = f'background-color: rgba(255, 0, 0, {min(abs(val)/20,1):.2f})'
    return color

display(indiv_sorted.style.applymap(color_pm, subset=['PM_p40']).format({
    'plus_minus': '{:.1f}',
    'o_poss': '{:.1f}',
    'd_poss': '{:.1f}',
    'pts_for': '{:.1f}',
    'pts_against': '{:.1f}',
    'minutes': '{:.2f}',
    'off_rtg': '{:.2f}',
    'def_rtg': '{:.2f}',
    'net_rtg': '{:.2f}',
    'PM_p40': '{:.2f}',
    'team_PM_p40':'{:.1f}',
    'team_off_rtg':'{:.1f}',
    'team_def_rtg':'{:.1f}'
}))

/var/folders/qh/zhr4gq8s5px2ff46zwfdk90hy3y30j/T/ipykernel_98387/1381822628.py:14: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  display(indiv_sorted.style.applymap(color_pm, subset=['PM_p40']).format({

## Individual Stats

In [19]:
import ipywidgets as widgets
from IPython.display import display
team_off_rtg = indiv['team_off_rtg'].iloc[0]
team_def_rtg = indiv['team_def_rtg'].iloc[0]
team_PM_p40 = indiv['team_PM_p40'].iloc[0]
def show_rating(rating_type):
    if rating_type == 'Offensive':
        display(indiv[['players', 'off_rtg']].sort_values('off_rtg', ascending=False).reset_index(drop=True))
    elif rating_type == 'PM_p40':
        display(indiv[['players', 'PM_p40']].sort_values('PM_p40', ascending=False).reset_index(drop=True))
    else:
        display(indiv[['players', 'def_rtg']].sort_values('def_rtg').reset_index(drop=True))
#can i add to the display a printed statement of total_off_rtg, total_def_rtg, total_pm_p40
    print(f"Total Offensive Rating: {team_off_rtg:.2f}")
    print(f"Total Defensive Rating: {team_def_rtg:.2f}")
    print(f"Total PM_p40: {team_PM_p40:.2f}")

dropdown = widgets.Dropdown(options=['Offensive', 'Defensive','PM_p40'], description='Rating:')
widgets.interactive(show_rating, rating_type=dropdown)

interactive(children=(Dropdown(description='Rating:', options=('Offensive', 'Defensive', 'PM_p40'), value='Off…

### Top 5 player combos by offensive turnover percentage (o_TOV%):

In [21]:
import itertools
import pandas as pd

# list of player shortcodes
players = ['LL', 'MH', 'AM7', 'AM', 'KJ', 'IK', 'JL', 'ZO', 'CH', 'MS', 'AC','PR']

# store results
combo_stats = []
min_minutes = 30  # set your minimum minutes threshold here
mask = ls['minutes'] >= min_minutes

for p1, p2 in itertools.combinations(players, 2):
    mask = ls['lineup'].str.contains(p1) & ls['lineup'].str.contains(p2)
    df_pair = ls[mask]

    if df_pair.empty:
        continue  # skip if this combo never played together

    agg = df_pair[['minutes', 'plus_minus', 'poss_total', 'o_poss', 'd_poss', 'pts_for', 'pts_against']].sum()

    # Compute o_TOV%
    if 'o_TOV%' in df_pair.columns and agg['o_poss'] > 0:
        total_turnovers = (df_pair['o_TOV%'] * df_pair['o_poss']).sum()
        o_tov = total_turnovers / agg['o_poss']
    else:
        o_tov = float('nan')

    combo_stats.append({
        'Combo': f"{p1}-{p2}",
        'Minutes': agg['minutes'],
        'o_TOV%': o_tov
    })

# Convert to DataFrame
combo_df = pd.DataFrame(combo_stats)
combo_df['o_TOV%'] = combo_df['o_TOV%'].round(2)
combo_df['Minutes'] = combo_df['Minutes'].round(2)

# Sort by o_TOV%
combo_df = combo_df.sort_values('o_TOV%', ascending=False)

# Display top 5
print("Top 5 player combos by offensive turnover percentage (o_TOV%):")
print(combo_df.head(10))

Top 5 player combos by offensive turnover percentage (o_TOV%):
     Combo  Minutes  o_TOV%
7    MH-KJ     0.88    1.08
40   IK-MS     2.27    0.51
17  AM7-IK     4.37    0.30
20  AM7-MS     4.57    0.29
45   JL-MS     7.66    0.29
51   CH-MS     3.63    0.26
16  AM7-KJ     8.52    0.25
41   IK-AC    38.23    0.23
34   KJ-MS     6.24    0.23
31   KJ-JL    25.76    0.22

In [17]:
import itertools
import pandas as pd

# list of player shortcodes
players = ['LL', 'MH', 'AM7', 'AM', 'KJ', 'IK', 'JL', 'ZO', 'CH', 'MS', 'AC','PR']

# store results
combo_stats = []

for p1, p2 in itertools.combinations(players, 2):
    mask = ls['lineup'].str.contains(p1) & ls['lineup'].str.contains(p2)
    df_pair = ls[mask]

    if df_pair.empty:
        continue  # skip if this combo never played together

    agg = df_pair[['minutes', 'plus_minus', 'poss_total', 'o_poss', 'd_poss', 'pts_for', 'pts_against']].sum()

    # Compute o_TOV%
    if 'd_TOV%' in df_pair.columns and agg['d_poss'] > 0:
        total_turnovers = (df_pair['d_TOV%'] * df_pair['d_poss']).sum()
        o_tov = total_turnovers / agg['d_poss']
    else:
        o_tov = float('nan')

    combo_stats.append({
        'Combo': f"{p1}-{p2}",
        'Minutes': agg['minutes'],
        'd_TOV%': o_tov
    })

# Convert to DataFrame
combo_df = pd.DataFrame(combo_stats)
combo_df = combo_df[combo_df['Minutes'] >= 30]  # Filter combos with at least 40 minutes played
combo_df['d_TOV%'] = combo_df['d_TOV%'].round(2)
combo_df['Minutes'] = combo_df['Minutes'].round(2)

# Sort by o_TOV%
combo_df = combo_df.sort_values('d_TOV%', ascending=False)

# Display top 5
print("Top 5 player combos by defensive turnover percentage (d_TOV%):")
print(combo_df.head(13))

Top 5 player combos by defensive turnover percentage (d_TOV%):
    Combo  Minutes  d_TOV%
42  ZO-AC    75.64    0.31
8   MH-AC    97.91    0.30
5   MH-ZO    82.20    0.28
33  IK-AC    49.35    0.27
30  IK-ZO    45.20    0.26
43  ZO-PR    66.44    0.26
20  AM-AC   110.52    0.26
45  CH-AC    97.28    0.25
9   MH-PR    73.83    0.25
49  AC-PR    75.32    0.24
6   MH-CH   140.46    0.23
40  ZO-CH    70.90    0.23
38  JL-AC    70.07    0.22

In [24]:
import itertools
import pandas as pd

# list of player shortcodes
players = ['LL', 'MH', 'AM7', 'AM', 'KJ', 'IK', 'JL', 'ZO', 'CH', 'MS', 'AC','PR']

# store results
combo_stats = []

for p1, p2, p3 in itertools.combinations(players, 3):
    mask = ls['lineup'].str.contains(p1) & ls['lineup'].str.contains(p2) & ls['lineup'].str.contains(p3)
    df_pair = ls[mask]

    if df_pair.empty:
        continue  # skip if this combo never played together

    agg = df_pair[['minutes', 'plus_minus', 'poss_total', 'o_poss', 'd_poss', 'pts_for', 'pts_against']].sum()

    # Compute o_TOV%
    if 'd_TOV%' in df_pair.columns and agg['d_poss'] > 0:
        total_turnovers = (df_pair['d_TOV%'] * df_pair['d_poss']).sum()
        o_tov = total_turnovers / agg['d_poss']
    else:
        o_tov = float('nan')

    combo_stats.append({
        'Combo': f"{p1}-{p2}-{p3}",
        'Minutes': agg['minutes'],
        'd_TOV%': o_tov
    })

# Convert to DataFrame
combo_df = pd.DataFrame(combo_stats)
combo_df = combo_df[combo_df['Minutes'] >= 40]  # Filter combos with at least 40 minutes played
combo_df['d_TOV%'] = combo_df['d_TOV%'].round(2)
combo_df['Minutes'] = combo_df['Minutes'].round(2)

# Sort by o_TOV%
combo_df = combo_df.sort_values('d_TOV%', ascending=False)

# Display top 5
print("Top 5 player combos by defensive turnover percentage (d_TOV%):")
print(combo_df.head(13))

Top 5 player combos by defensive turnover percentage (d_TOV%):
       Combo  Minutes  d_TOV%
18  MH-AM-ZO    55.38    0.30
21  MH-AM-AC    48.52    0.30
83  AM-ZO-AC    40.20    0.30
72  AM-IK-ZO    41.50    0.29
84  AM-ZO-PR    43.38    0.28
90  AM-AC-PR    44.57    0.26
34  MH-JL-CH    89.33    0.25
73  AM-IK-CH   112.63    0.24
82  AM-ZO-CH    55.20    0.24
78  AM-JL-CH   101.01    0.24
16  MH-AM-IK   107.10    0.24
19  MH-AM-CH   114.00    0.24
29  MH-IK-CH    89.03    0.23

In [25]:
import itertools
import pandas as pd

# list of player shortcodes
players = ['LL', 'MH', 'AM7', 'AM', 'KJ', 'IK', 'JL', 'ZO', 'CH', 'MS', 'AC','PR']

# store results
combo_stats = []

for p1, p2, p3 in itertools.combinations(players, 3):
    mask = ls['lineup'].str.contains(p1) & ls['lineup'].str.contains(p2) & ls['lineup'].str.contains(p3)
    df_pair = ls[mask]

    if df_pair.empty:
        continue  # skip if this combo never played together

    agg = df_pair[['minutes', 'plus_minus', 'poss_total', 'o_poss', 'd_poss', 'pts_for', 'pts_against']].sum()

    # Compute o_TOV%
    if 'o_orbR' in df_pair.columns and agg['o_poss'] > 0:
        total_orb = (df_pair['o_orbR'] * df_pair['o_poss']).sum()
        o_orb = total_orb / agg['o_poss']
    else:
        o_orb = float('nan')

    combo_stats.append({
        'Combo': f"{p1}-{p2}-{p3}",
        'Minutes': agg['minutes'],
        'o_orbR': o_orb
    })

# Convert to DataFrame
combo_df = pd.DataFrame(combo_stats)
combo_df = combo_df[combo_df['Minutes'] >= 10]  # Filter combos with at least 40 minutes played
combo_df['o_orbR'] = combo_df['o_orbR'].round(2)
combo_df['Minutes'] = combo_df['Minutes'].round(2)

# Sort by o_orbR
combo_df = combo_df.sort_values('o_orbR', ascending=False)
# Display top 5
print("Top 5 player combos by offensive rebound rate (o_orbR):")
display(combo_df.head(13))

Top 5 player combos by offensive rebound rate (o_orbR):

        Combo  Minutes  o_orbR
91   KJ-IK-JL    16.48    0.55
114  IK-JL-PR    27.25    0.39
95   KJ-IK-AC    15.71    0.37
100  KJ-JL-AC    16.99    0.34
65   AM-KJ-JL    15.67    0.32
37   MH-JL-PR    23.34    0.32
98   KJ-JL-CH    15.42    0.30
109  KJ-AC-PR    16.93    0.29
64   AM-KJ-IK    25.28    0.29
129  JL-AC-PR    14.33    0.28
113  IK-JL-AC    17.54    0.28
33   MH-JL-ZO    13.96    0.28
105  KJ-CH-AC    16.87    0.27

In [26]:
import itertools
import pandas as pd

# list of player shortcodes
players = ['LL', 'MH', 'AM7', 'AM', 'KJ', 'IK', 'JL', 'ZO', 'CH', 'MS', 'AC','PR']

# store results
combo_stats = []

for p1, p2 in itertools.combinations(players, 2):
    mask = ls['lineup'].str.contains(p1) & ls['lineup'].str.contains(p2)
    df_pair = ls[mask]

    if df_pair.empty:
        continue  # skip if this combo never played together

    agg = df_pair[['minutes', 'plus_minus', 'poss_total', 'o_poss', 'd_poss', 'pts_for', 'pts_against']].sum()

    # Compute o_TOV%
    if 'o_orbR' in df_pair.columns and agg['o_poss'] > 0:
        total_orb = (df_pair['o_orbR'] * df_pair['o_poss']).sum()
        o_orb = total_orb / agg['o_poss']
    else:
        o_orb = float('nan')

    combo_stats.append({
        'Combo': f"{p1}-{p2}",
        'Minutes': agg['minutes'],
        'o_orbR': o_orb
    })

# Convert to DataFrame
combo_df = pd.DataFrame(combo_stats)
combo_df = combo_df[combo_df['Minutes'] >= 10]  # Filter combos with at least 40 minutes played
combo_df['o_orbR'] = combo_df['o_orbR'].round(2)
combo_df['Minutes'] = combo_df['Minutes'].round(2)

# Sort by o_orbR
combo_df = combo_df.sort_values('o_orbR', ascending=False)
# Display top 5
print("Top 5 player combos by offensive rebound rate (o_orbR):")
display(combo_df.head(19))

Top 5 player combos by offensive rebound rate (o_orbR):

     Combo  Minutes  o_orbR
31   KJ-JL    25.76    0.41
30   KJ-IK    35.50    0.35
36   KJ-PR    22.27    0.34
47   JL-PR    39.56    0.31
15  AM7-AM    13.14    0.29
33   KJ-CH    30.19    0.26
37   IK-JL   112.77    0.26
42   IK-PR    49.21    0.26
46   JL-AC    46.48    0.25
35   KJ-AC    39.23    0.24
24   AM-JL   132.69    0.23
32   KJ-ZO    24.03    0.23
43   JL-ZO    16.68    0.23
22   AM-KJ    48.41    0.23
21  AM7-AC    10.80    0.22
9    MH-JL   119.88    0.22
14   MH-PR    45.78    0.20
44   JL-CH   115.33    0.20
8    MH-IK   120.01    0.19

In [21]:
print(indiv['players'].unique())

['PR' 'MH' 'AM' 'JL' 'KJ' 'AC' 'IK' 'ZO' 'CH' 'MS' 'AM7']

In [22]:
players = ['LL' 'MH' 'AM7' 'AM' 'KJ' 'IK' 'JL' 'ZO' 'CH' 'MS' 'AC']
# Filter lineups containing both "AC" and "MS"
mask = ls['lineup'].str.contains('JL') & ls['lineup'].str.contains('AM')
df_ac_ms = ls[mask]

# Sum up the necessary statistics
agg = df_ac_ms[['minutes', 'plus_minus', 'poss_total', 'o_poss', 'd_poss', 'pts_for', 'pts_against']].sum()

# Recalculate PM_p40 (plus_minus per 40 minutes)
agg['PM_p40'] = agg['plus_minus'] / agg['minutes'] * 40 if agg['minutes'] > 0 else float('nan')

# Recalculate off_rtg (Offensive Rating: points scored per 100 possessions)
agg['off_rtg'] = agg['pts_for'] / agg['o_poss'] * 100 if agg['o_poss'] > 0 else float('nan')

# Recalculate def_rtg (Defensive Rating: points allowed per 100 possessions)
agg['def_rtg'] = agg['pts_against'] / agg['d_poss'] * 100 if agg['d_poss'] > 0 else float('nan')

# Recalculate o_TOV% (Turnover Percentage: turnovers per 100 possessions)
# If 'o_TOV%' exists in df_ac_ms, we need to aggregate turnovers and possessions
if 'o_TOV%' in df_ac_ms.columns:
    # o_TOV% = total_turnovers / total_o_poss
    # First, estimate total turnovers from o_TOV% * o_poss for each row, then sum
    total_turnovers = (df_ac_ms['o_TOV%'] * df_ac_ms['o_poss']).sum()
    agg['o_TOV%'] = total_turnovers / agg['o_poss'] if agg['o_poss'] > 0 else float('nan')

    # Round numeric values to 2 decimal places
    agg = agg.round(2)
# Display the aggregate statistics
print("Aggregate statistics for lineups with both JL and AM:")
display(agg)

Aggregate statistics for lineups with both JL and AM:

minutes        148.09
plus_minus      22.00
poss_total     493.09
o_poss         249.15
d_poss         243.94
pts_for        301.00
pts_against    279.00
PM_p40           5.94
off_rtg        120.81
def_rtg        114.37
o_TOV%           0.14
dtype: float64